# Generated by Django 4.1.7 on 2023-03-10 09:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('apteka', '0002_positioncheck'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='check',
            name='title',
        ),
        migrations.RemoveField(
            model_name='positioncheck',
            name='salesman',
        ),
        migrations.AlterField(
            model_name='check',
            name='salesman',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='checks', to='apteka.salesman', verbose_name='Продавец'),
        ),
    ]
