# Generated by Django 4.1.7 on 2024-02-16 06:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('apteka', '0003_remove_check_title_remove_positioncheck_salesman_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='check',
            name='date_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Дата продажи'),
        ),
        migrations.AlterField(
            model_name='positioncheck',
            name='sale',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='positions', to='apteka.check', verbose_name='Номер заказа'),
        ),
    ]
